#!/usr/bin/env python3
"""Rebuild a read-only output-capacitor evidence review from supplied local sources.
Vendor downloads stay outside the public output directory. No CAD files are edited.
"""
import argparse, bisect, csv, hashlib, itertools, json, pathlib, re, xml.etree.ElementTree as ET
ap=argparse.ArgumentParser();ap.add_argument('--project',required=True);ap.add_argument('--private-sources',required=True);ap.add_argument('--out',required=True);a=ap.parse_args()
p=pathlib.Path(a.project);private=pathlib.Path(a.private_sources);out=pathlib.Path(a.out);out.mkdir(parents=True,exist_ok=True)
def sha(f):return hashlib.sha256(f.read_bytes()).hexdigest()
def write(n,v): (out/n).write_text(json.dumps(v,indent=2)+'\n')
master=p/'cad/recovery-physical-candidate/master.xml';r=ET.parse(master).getroot();comps={c.attrib['ref']:c.findtext('value') for c in r.findall('./components/comp')};nets={}
for n in r.findall('./nets/net'):
 for node in n.findall('node'):nets.setdefault(node.attrib['ref'],[]).append({'pin':node.attrib['pin'],'net':n.attrib['name']})
caprefs=['C201','C218','C223','C228','C206','C207','C208','C212','C213','C214']
assert len(set(caprefs))==10
for ref in caprefs:assert comps[ref].startswith('47uF' if ref in caprefs[:4] else '22uF')
rails=[]
for ref,cap,v,imax,lo,hi,rt,rb in [('U21',['C201'],.7992,4,.72,.88,'R201','R202'),('U24',['C218'],1.1196,3,1.06,1.17,'R207','R208'),('U25',['C223'],1.8,2,1.62,1.98,'R210','R211'),('U26',['C228'],3.318,3,2.97,3.63,'R213','R214'),('U22',['C206','C207','C208'],.8,4,.72,.88,None,None),('U23',['C212','C213','C214'],.8,4,.72,.88,None,None)]:
 rails.append({'regulator_ref':ref,'regulator_mpn':comps[ref],'capacitor_refs':cap,'output_net':next(x['net'] for x in nets[cap[0]] if x['net']!='GND'),'nominal_V':v,'converter_rated_output_A':imax,'output_Ceff_floor_uF':10 if len(cap)==1 else 30,'guide_screen_voltage_range_V':[lo,hi],'guide_range_limit':'Existing project rail-budget input only; not a complete installed-rail qualification or transient guarantee.','divider':None if not rt else {rt:comps[rt],rb:comps[rb]},'Ceff_status':'NOT_QUALIFIED'})
write('active-master-snapshot.json',{'master':'cad/recovery-physical-candidate/master.xml','sha256':sha(master),'scope':'Read-only; exact ten positions retained; no capacitor selection or CAD edits.','total_references':len(comps),'reviewed_capacitors':[{'reference':x,'value':comps[x],'nets':nets[x]} for x in caprefs],'rails':rails,'relevant_components':{x:comps[x] for x in ['C202','C219','C224','C229','R205','R206','L21','L22','L23','L24','L25','L26']}})
sources=[]
for manifest in ['initial-fetch.json','spec-fetch.json','ti-fetch.json']:
 for z in json.loads((private/manifest).read_text()):
  assert 'error' not in z,z
  z['checked_UTC_date']='2026-10-03';z['private_original_retained']=True;sources.append(z)
write('source-manifest.json',{'sources':sources,'public_artifact_policy':'Original PDFs, HTML, extracted complete text/curves and screenshots are retained outside this deliverable. Only factual extracted dimensions, short evidence summaries, derived engineering calculations, source URLs and hashes are distributed.','source_authorship':'Samsung and TI manufacturer-authored originals fetched directly from manufacturer endpoints.','historical_pdf_hash_comparison':{'CL32B476KQVVPN-specsheet.pdf':'Identical to historical candidate-review SHA256','CL31B226KPHNNN-specsheet.pdf':'Identical to historical candidate-review SHA256'}})
parts=[{'mpn':'CL32B476KQVVPNE','nominal_uF':47,'rated_V':6.3,'tolerance_percent':10,'dielectric':'X7R','manufacturer_page_status':'Mass Production','case_inch':'1210','body_nominal_LWT_mm':[3.2,2.5,2.5],'body_tolerance_LWT_mm':[.4,.3,.3],'body_min_LWT_mm':[2.8,2.2,2.2],'body_max_LWT_mm':[3.6,2.8,2.8],'termination_BW_nominal_tolerance_mm':[.6,.3],'specification_issued':'2024-06-26','dimension_source_page':1,'manufacturer_reflow_status':'NO_EXACT_APPLICABLE_ROW_FOUND','manufacturer_reflow_source_page':34,'rejected_reflow_row':'3225 +/-0.30 mm does not cover exact +/-0.40 mm length.','rejected_flow_row':'Page 35 FLOW table 3225 +/-0.40 mm is not a reflow recommendation.','rejected_test_PCB_rows':'Pages 3-4 adhesive/bend/reliability test substrates are not production reflow land recommendations.'},{'mpn':'CL31B226KPHNNNE','nominal_uF':22,'rated_V':10,'tolerance_percent':10,'dielectric':'X7R','manufacturer_page_status':'Mass Production','case_inch':'1206','body_nominal_LWT_mm':[3.2,1.6,1.6],'body_tolerance_LWT_mm':[.2,.2,.2],'body_min_LWT_mm':[3,1.4,1.4],'body_max_LWT_mm':[3.4,1.8,1.8],'termination_BW_nominal_tolerance_mm':[.5,.3],'specification_issued':'2021-04-15','dimension_source_page':1,'manufacturer_reflow_status':'APPLICABLE_3216_PLUS_MINUS_0P20_ROW','manufacturer_reflow_source_page':33,'manufacturer_reflow_ranges_mm':{'inner_gap_a':[1.64,1.76],'each_pad_length_b':[1.19,1.31],'pad_width_c':[1.74,1.86],'total_copper_span':[4.02,4.38]},'midpoint_choice_mm':{'inner_gap':1.7,'pad_size_xy':[1.25,1.8],'pad_centers_x':[-1.475,1.475],'copper_envelope_xy':[4.2,1.8]},'max_range_choice_mm':{'inner_gap':1.76,'pad_size_xy':[1.31,1.86],'pad_centers_x':[-1.535,1.535],'copper_envelope_xy':[4.38,1.86]},'assembly_status':'Manufacturer range verified, but paste/mask/placement/courtyard and actual assembly remain unqualified.'}]
proposal={'mpn':parts[0]['mpn'],'status':'UNSELECTED_ENGINEERING_DERIVED_REVIEW_PROPOSAL_ONLY_NOT_MANUFACTURER_RECOMMENDATION','selected':False,'purpose':'Conservative terminal-coverage starting geometry; not a released footprint or optimized land.','minimum_missing_source_input':'A manufacturer-authored reflow drawing explicitly applicable to CL32B476KQVVPNE and its exact L/W/BW/termination tolerances, or an accountable assembly-engineering approved copper/mask/paste drawing with a documented process tolerance stack and validation for this exact part. Manufacturer applicability alone does not qualify the production assembly process.','pad_centers_xy_mm':[[-1.675,0],[1.675,0]],'pad_size_xy_mm':[1.65,3.2],'inner_gap_mm':1.7,'nominal_copper_envelope_xy_mm':[5,3.2],'analyst_assumptions':{'placement_translation_each_axis_mm':.1,'independent_copper_edge_error_mm':.05,'placement_rotation_deg':0,'courtyard_clearance_each_side_mm':.25},'fabrication_expanded_copper_envelope_xy_mm':[5.1,3.3],'illustrative_courtyard_xy_mm':[5.6,3.8],'limits':['No placement-rotation allowance is proven.','No solder paste, mask, wetting, flex/strain, tombstone, thermal-cycle, solder-joint-life or reflow qualification.','Large pad/fillet geometry is not automatically better reliability.','No clearance or courtyard dimension is a universal manufacturer minimum.','Do not silently substitute the generic +/-0.30 row or FLOW row.']}
checks=[]
for L,W,BW,dx,dy in itertools.product([2.8,3.6],[2.2,2.8],[.3,.9],[-.1,.1],[-.1,.1]):
 for side in [-1,1]:
  end=side*L/2+dx;inner=side*(L/2-BW)+dx;terminal=sorted([end,inner]);pad=[.9,2.45] if side==1 else [-2.45,-.9]
  overlap=max(0,min(pad[1],terminal[1])-max(pad[0],terminal[0]));toe=2.45-(side*end);sidemargin=1.55-(W/2+abs(dy));checks.append({'L':L,'W':W,'BW':BW,'dx':dx,'dy':dy,'terminal_side':side,'axial_copper_overlap_mm':round(overlap,9),'toe_extension_mm':round(toe,9),'minimum_side_extension_mm':round(sidemargin,9)})
proposal['geometry_corner_checks']={'count':len(checks),'minimum_axial_overlap_mm':min(x['axial_copper_overlap_mm'] for x in checks),'minimum_toe_extension_mm':min(x['toe_extension_mm'] for x in checks),'minimum_side_extension_mm':min(x['minimum_side_extension_mm'] for x in checks),'minimum_pad_gap_under_edge_error_mm':1.6,'interpretation':'Bounding-box geometry only under stated independent dimensional/translation/copper-edge assumptions; all corners enumerated.'}
assert proposal['geometry_corner_checks']['minimum_axial_overlap_mm']>=.3
assert proposal['geometry_corner_checks']['minimum_side_extension_mm']>=.05
write('geometry-review.json',{'units':'mm','parts':parts,'engineering_derived_47uF_proposal':proposal,'no_CAD_change':True})
with (out/'derived-47uF-corner-checks.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=list(checks[0]));w.writeheader();w.writerows(checks)
curves=[]
for key,nominal,volts in [('CL32B476KQVVPN',47,[.7992,.88,1.1196,1.17,1.8,1.98,3.318,3.63]),('CL31B226KPHNNN',22,[.8,.88,1.675])]:
 data=json.loads((private/(key+'-graphs.json')).read_text());g=next(x for x in data if x['graphType']=='DCBias')['selectPartsList'][0];pts=[(float(t['x']),float(t['y'])) for t in g['chartList'][0]['data']];pts.sort();xs=[x for x,y in pts]
 for voltage in volts:
  i=bisect.bisect_right(xs,voltage);x0,y0=pts[i-1];x1,y1=pts[i];delta=y0+(y1-y0)*(voltage-x0)/(x1-x0);c=nominal*(1+delta/100)
  curves.append({'mpn':key+'E','voltage_V':voltage,'typical_C_each_uF':round(c,6),'typical_C_bank_uF':round(c*(3 if nominal==22 else 1),6),'measurement_frequency_Hz':g['dsDcFre'],'measurement_AC_Vrms':g['dsDcSign'],'measurement_temperature_C':g['degC'],'interpolation':'linear between adjacent manufacturer points','qualification':'NONE; typical 25C bias curve only; no combined lower bound','converter_endpoint_only':voltage==1.675})
write('electrical-limits.json',{'rails':rails,'typical_curve_spot_checks':curves,'gates':{'47uF_single_Ceff_floor_uF':10,'22uF_three_part_bank_Ceff_floor_uF':30,'22uF_each_equal_share_uF':10,'minimum_all_effect_retention_nominal_47uF':10/47,'minimum_all_effect_retention_nominal_22uF':10/22,'remaining_retention_after_initial_minus10_percent_47uF':10/(47*.9),'remaining_retention_after_initial_minus10_percent_22uF':10/(22*.9)},'TI_table_context':{'TPS6282xA':'Rev I, section 8.2.2.5 / p14: 10uF effective output; table 8-3 / p13 includes 0.47uH with 47uF nominal, anticipates +20/-35% capacitance variation. 47*0.65=30.55uF is the lower edge of that nominal-row assumed variation, not a replacement for the separate 10uF floor.','TPS628640B':'Rev C, section 9.2.1.2.5 / p22: recommended minimum 30uF effective output; table 9-3 / p21 includes 0.24uH with 3x22uF, anticipates +20/-30% capacitance variation. 66*0.70=46.2uF is that row lower edge. If the combined application envelope falls outside the anticipated row, independent loop/transient validation is required.','voltage':'CPU/KPU 56.2k start selection gives 0.8V. 1.675V is the converter register endpoint only; it is outside the existing K230 0.72-0.88V screen and is not an approved SoC voltage.','current':'Converter ratings are CORE 4A, DDR 3A, 1V8 2A, 3V3 3A, CPU/KPU 4A each; these are not capacitor ripple ratings or demonstrated installed rail capacity. TPS62864 warns reduced lifetime at continuous 4A with junction above105C.'},'qualification_gaps':['Actual peak rail voltage, startup/overshoot and permissible CPU/KPU operating setpoints','Combined lower-bound capacitance over DC bias, actual small AC ripple and frequency, capacitor temperature, initial tolerance, aging, lot/process variation','MLCC ripple-current heating and ESR/ESL at actual converter spectrum and current sharing','LC/loop stability, transients, startup/inrush and local placement under chosen component envelopes','Installed temperature in the provisional85C enclosure;125C capacitor rating does not show40C usable thermal margin','Exact47uF reflow recommendation absent; derived proposal requires assembly review'],'Murata0805_status':'No selection, value/count change or geometry reduction. Missing combined Ceff evidence remains blocking.','no_BOM_or_CAD_changes':True})
write('verification.json',{'active_master_sha256_before':sha(master),'active_master_sha256_after':sha(master),'all_requested_capacitor_references_present':True,'47uF_count':4,'22uF_count':6,'manufacturer_reflow_pages_visually_inspected':[{'file':'CL32B476KQVVPN-specsheet.pdf','page':34},{'file':'CL31B226KPHNNN-specsheet.pdf','page':33}],'originals_retained_outside_public_deliverable':True,'derived47_geometry_corner_count':len(checks),'assembly_qualified':False,'Ceff_qualified':False,'CAD_or_BOM_edited':False,'additional_source_pages_visually_inspected':[{'file':'CL32B476KQVVPN-specsheet.pdf','page':1},{'file':'CL31B226KPHNNN-specsheet.pdf','page':1},{'file':'tps62827.pdf','page':13},{'file':'tps62864.pdf','page':21}]})
print(json.dumps({'master_sha256':sha(master),'files_written':len(list(out.iterdir())),'curve_spot_checks':curves,'geometry_corner_summary':proposal['geometry_corner_checks']},indent=2))
